/* Autogenerated by png2wx.pl on Thu Nov 22 12:06:07 2018 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);
extern void deinitialize_images(void);

extern wxBitmap *_img_LIVI_Depth_model;
extern wxBitmap *_img_LIVI_Depth_model_pi;

#endif /* ICONS_H */
