/* Autogenerated by png2wx.pl on Thu Nov 29 12:49:35 2018 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);
extern void deinitialize_images(void);

extern wxBitmap *_img_LIVI_Depth_model;
extern wxBitmap *_img_LIVI_Depth_model_pi;
extern wxBitmap *_img_DepthViewer;
extern wxBitmap *_img_DepthViewerRollover;
extern wxBitmap *_img_DepthViewerToggled;

#endif /* ICONS_H */
